### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by TomDLT** [benchopt/template_benchmark#6]
The steps described in the README are not super clear.
```
- Hit the Use this template button,
- Create the repo,
- Clone it on your computer,
```
Where is the "Use this template button"? What it "the repo"? What is "it"?

**Comment by tomMoral** [comment]
Is it better now or are some instruction still unclear?

**Comment by TomDLT** [comment]
Great!

**Comment by Sandy4321** [comment]
yes it is not clear at all what it is and how to use
may you share video from zero to end for project?

**Comment by tomMoral** [comment]
Hello,

thanks for your feedback.
We are planning to release a video at some point but it got a bit delayed.

In the mean time, could you share what is unclear to you in the current instructions?

Thanks again.
